### ISSUE TITLE
Can you add the cookie graphic like it was in earlier version?

### ISSUE THREAD

**Issue by djaffer** [xavierbriole/react-cookienotice#125]
Hi, I see some popups on sites that are exactly like this but have the cookie pic. Due to that reason, I am still using the older version?

![image](https://user-images.githubusercontent.com/5740725/175959654-3b2d4d13-a61a-4018-a68e-546d08c83b6c.png)

**Comment by xavierbriole** [comment]
Hello @djaffer 

It's not planned to re-add the cookie icon in the version 5.x because the design is not built for this. You can still rewrite labels with this icon (copy/paste: 🍪) and insert it in the labels you want! :)

**Comment by djaffer** [comment]
Couldn't find any versions for "react-cookienotice" that matches "^4.3.0"

**Comment by djaffer** [comment]
thank you!
