### ISSUE TITLE
I am using reactjs. 

### ISSUE THREAD

**Issue by TrushantB** [xavierbriole/react-cookienotice#156]
<img width="984" alt="Screenshot 2023-04-15 at 8 38 36 AM" src="https://user-images.githubusercontent.com/43570507/232180072-1dd11c97-767d-460b-9bc9-225d4ded34ff.png">

**Comment by xavierbriole** [comment]
Hello,
What's the version of react-cookienotice package ?
Which version of React & Node and what is the framework that bundle your App ? (CRA, Next, Vite, etc)
