### ISSUE TITLE
Cannot build Next.js app because "document is not defined in react-cookienotice.es.js"

### ISSUE THREAD

**Issue by simonlopezwork** [xavierbriole/react-cookienotice#189]
Hi Xavier, 

Awesome notice first and foremost!

My app was not building in production so I spinned out a fresh non-TS Next.js app. On development, these errors show up in the console/terminal:

![image](https://github.com/xavierbriole/react-cookienotice/assets/52769185/4d7570dd-770e-4515-ac22-c665bc2f78a7)

These errors are present in the fresh next install and in the main app.

When building, these errors show up on multiple pages and Nextjs fails to build.

![image](https://github.com/xavierbriole/react-cookienotice/assets/52769185/8670c56e-ae8b-4fdc-84c8-4aa82d52faca)

Would like to know your thoughts on the fix. Thanks!

**Comment by xavierbriole** [comment]
Hello! Thank you for the report, I will take a look on it. To test on my side, i just need to create an empty Next.js app? Nothing more?

**Comment by simonlopezwork** [comment]
Yes, I think so because they have the same error.

I forgot to mention that I wrapped the CookieNotice component in a Nextjs
client component via the "use client" directive.

Thanks again!

**Comment by xavierbriole** [comment]
Ok I reproduced. Will try to find a fix.

**Comment by simonlopezwork** [comment]
Successfullly deployed the app. Thank you very much for being so prompt!
