### ISSUE TITLE
Textlabel isn't shown

### ISSUE THREAD

**Issue by raining-tr** [xavierbriole/react-cookienotice#37]
The text for the cookieTextLabel is not showing at all, the text is there, but greyed out.

![grafik](https://user-images.githubusercontent.com/62763434/98893564-f2b23800-24a2-11eb-916b-64c03d5e22c1.png)
![grafik](https://user-images.githubusercontent.com/62763434/98893578-f940af80-24a2-11eb-8f0d-7b6833215105.png)

**Comment by xavierbriole** [comment]
Hello @raining-tr !

Hmm, it seems to be a CSS issue 🕵🏻‍♂️

Can you provide an URL to check or it's on you local ?

**Comment by raining-tr** [comment]
Hello Xavier,

I found the issue. It is an issue with "cookie-text" in CookieText.js at line 24. Simply change [...] className="cookie-text" to className="CookieText" - it will display the text correctly.

**Comment by xavierbriole** [comment]
It confirms that something is overriding the text color in the CSS, I will release the fix in few hours by prefixing all classNames 🚀

Thank you for the issue 😄

(please keep this issue open)
