### ISSUE TITLE
Add prop for dark / light theme

### ISSUE THREAD

**Issue by jacobedawson** [xavierbriole/react-cookienotice#44]
Hi, react-cookienotice is great, easy to add and looks great. However, the 'prefers-color-theme' media rule that forces a style is a bit annoying, really a simple true false prop would make it a much friendlier dev experience. I see that you've added a note to add that.

**Comment by xavierbriole** [comment]
Hello @jacobedawson !

Thanks 🙏🏻
Alright, I will make this feature high priority.

**Comment by xavierbriole** [comment]
Duplicate of #26 (just for my information)
