### ISSUE TITLE
Using this library

### ISSUE THREAD

**Issue by AryanBeezadhur** [xavierbriole/react-cookienotice#53]
Hi, really nice lib!

I'm planning to use this in a React app, but first I had two questions:

1. This is production-ready, isn't it?
2. Can I install it with `npm i react-cookienotice` instead of `yarn`?

Thanks

**Comment by xavierbriole** [comment]
Hello @AryanBeezadhur!

Thanks!! That means so much 😍

For your questions:
1. Yes it's production ready, if the result on your local dev is satisfying :) 
2. Sure, you can use npm instead of yarn by typing `npm i react-cookienotice` (I should add it to the readme)

**Comment by AryanBeezadhur** [comment]
Thanks!

I will definitely be using this.
