### ISSUE TITLE
Is there a way to register an accept click handler

### ISSUE THREAD

**Issue by rluvaton** [xavierbriole/react-cookienotice#66]
Great project!

Is there a way to register a callback for the accept button so I can load the cookies only if the user click accept?

**Comment by xavierbriole** [comment]
Hello @rluvaton !

Thank you 😄 

Are you talking about a function that would be called when the user click on the accept button so you could do your own code where the CookieNotice component is rendered ?
If yes, there is no handler like this atm but it's something interesting that can be done.
You can submit a PR or I can do it, it's as you want.

**Comment by rluvaton** [comment]
Wow, that was quick! Thank you!
