### ISSUE TITLE
Add `scrollToAccept` feature

### ISSUE THREAD

**Issue by xavierbriole** [xavierbriole/react-cookienotice#7]
When user scroll to some px, the cookie notice should be accepted and closed
With progress bar

**Comment by AryanBeezadhur** [comment]
This would go against GDPR since the user is required to explicitly click on the <kbd>accept</kbd> button to accept cookie use.

**Comment by xavierbriole** [comment]
Indeed ... just found it : https://www.termsfeed.com/blog/gdpr-scrolling-not-consent/

Thanks for the information ! (tbh I'm a little bit disappointed 😄)
