### ISSUE TITLE
Bug - when cookies allowed cookienotice prevent from clicking behind it

### ISSUE THREAD

**Issue by rluvaton** [xavierbriole/react-cookienotice#72]
When cookies are allowed, this library set the `opacity` to `0` on the containing `div`, but `opacity` still take space AND you can still click on it, which means that you can press the learn more even when the notice is hidden

A possible solution is to set `display: none;` or to not render the component at all (preferred as  you don't use it anyway)...

----

**A useful table (from [SO](https://stackoverflow.com/a/273076/5923666)):**

Here is a compilation of verified information from the various answers.

Each of these CSS properties is unique. In addition to rendering an element not visible, they have the following additional effect(s):

0. **Collapses** the space that the element would normally occupy
0. Responds to **events** (e.g., click, keypress)
0. Participates in the **taborder**

<pre>
                     collapse events taborder
opacity: 0              No     Yes     Yes
visibility: hidden      No     No      No
visibility: collapse   Yes*    No      No
display: none          Yes     No      No

* Yes inside a table element, otherwise No.
</pre>

**Comment by xavierbriole** [comment]
How could I have missed this bug? 😱
Thanks, I will check ASAP.

**Comment by rluvaton** [comment]
If you want a quick fix you can take a look at my patch [here](https://github.com/rluvaton/dribbble-shots-recreation/blob/fix/25-cant-click--cookie-notice-prev-position-when-hidden/src/common/components/CookieInjector/index.css)
