### ISSUE TITLE
github default branch is master

### ISSUE THREAD

**Issue by creharmony** [xavierbriole/react-cookienotice#75]
Hi, when arriving on github project, the default branch is 'master'
so the readme we are reading is deprecated.

for exemple, there is no need ton include css file (wich doesn't exist anymore)
this introduce some confusion

would be great to advancde master branch to the last published version

**Comment by xavierbriole** [comment]
Sorry for the confusion.
v4.0.0 is published, it's should be ok now :)

**Comment by creharmony** [comment]
it's ok, npm install provide `node_modules/react-cookienotice/dist/index.css` file 👍
