### ISSUE TITLE
footer hover once cookies accepted

### ISSUE THREAD

**Issue by creharmony** [xavierbriole/react-cookienotice#78]
I've a footer on my website,

If I add react-cookienotice, and once cookies are accepted, I'm not able to click on footer link anymore. There is a div that is over my component and prevent me to click on link
![image](https://user-images.githubusercontent.com/74717011/133927061-cfbfcb5d-bdbc-4d1f-9b09-abbed70498f3.png)

**Comment by xavierbriole** [comment]
Hello,

It's fixed in version 4.0.0 🚀
